[project]
name = "burger-king-analysis"
version = "0.1.0"
description = " A simple analysis on a burger king dataset."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
    "jupyter"
]
